spring:
  datasource:
    url: jdbc:mysql://localhost:3307/securecapita
    username: root
    password: root
  jpa:
    generate-ddl: off
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        globally_quoted_identifiers: true # identifiers in quotes -> if using keywords from DB, there will be no conflict
        format_sql: true
  sql:
    init:
      mode: never
      continue-on-error: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration